default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-check
        name: cargo check
        entry: cargo check --all-targets --all-features
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-test
        name: cargo test
        entry: cargo test --all-features
        language: system
        pass_filenames: false
        stages: [pre-push]
